### ISSUE TITLE
redis实战的原文连接连接跳转不了

### ISSUE THREAD

**Issue by ming1ing** [gdut-yy/gdut-yy.github.io#2]
redis实战的原文连接连接跳转不了

![image](https://user-images.githubusercontent.com/22784544/196142684-ce0148fc-fde5-46ca-a351-c809c549dbc2.png)

![image](https://user-images.githubusercontent.com/22784544/196142560-d92c01f6-2c44-4c95-a851-a401d34b34f3.png)

**Comment by gdut-yy** [comment]
fixed by b3312234a6e0e4df61f91086a179150838ff2fad
