### ISSUE TITLE
跳转内容和跳转说明不一致

### ISSUE THREAD

**Issue by ming1ing** [gdut-yy/gdut-yy.github.io#3]
https://gdut-yy.github.io/doc-gitblogs/module_algo/math/number-theory/#%E8%A3%B4%E8%9C%80%E5%AE%9A%E7%90%86

![image](https://user-images.githubusercontent.com/22784544/218927794-39038fb9-d1b2-4b7a-9f0e-9b033ffb88e2.png)
- 裴蜀定理写了`分解质因数`，跳转又是`裴蜀定理`
https://oi-wiki.org/math/number-theory/bezouts/

**Comment by gdut-yy** [comment]
fixed by 5eb7687
